In [ ]:
from fastai2.torch_basics import *
from fastai2.data.all import *
from fastai2.vision.core import *

In [ ]:
source = untar_data(URLs.MNIST_TINY)/'train'
items = get_image_files(source)
fn = items[0]
fn

PosixPath('/home/quantran/.fastai/data/mnist_tiny/train/7/9286.png')

In [ ]:
type(array(3))

numpy.ndarray

In [ ]:
def neg(x): return -x

In [ ]:
neg((1,2))

TypeError: bad operand type for unary -: 'tuple'

In [ ]:
neg(array((1,2)))

array([-1, -2])

# Transform decorator can make a function work in a flexible way (inputs with different type)

Class decorator

In [ ]:
@Transform
def neg(x): return -x

This @Transform looks like you gonna pass the func (neg) in ```__init__``` of class Transform

In [ ]:
# equivalent
def _neg(x): return -x
neg = Transform(_neg)

In [ ]:
neg((1,2)) # this is like calling encode function in Transform class

(-1, -2)

In [ ]:
img = load_image(fn)
img

In [ ]:
img.shape

(28, 28)

In [ ]:
type(img)

PIL.Image.Image

In [ ]:
t = tensor(array(img))
t[12:14]

tensor([[  0,   0,   0,   0,   0,   0,   0,   0, 164, 239,  26,   0,   0,   0,
           0,  96, 236,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,  12,  47,   0,   0,   0,   0,
           0, 179, 235,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],
       dtype=torch.uint8)

In [ ]:
neg(t[12:14]) # negative here doesn't really work, due to type uint8 doesn't allow negative number

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,  92,  17, 230,   0,   0,   0,
           0, 160,  20,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0, 244, 209,   0,   0,   0,   0,
           0,  77,  21,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],
       dtype=torch.uint8)

In [ ]:
t_float = t.float()
neg(t_float[12:14])

tensor([[  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0., -164., -239.,
          -26.,   -0.,   -0.,   -0.,   -0.,  -96., -236.,   -0.,   -0.,   -0.,
           -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
        [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,  -12.,  -47.,
           -0.,   -0.,   -0.,   -0.,   -0., -179., -235.,   -0.,   -0.,   -0.,
           -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.]])

## Note that @Transform will reserve type (see below, search for 'reserve')

# Quick note on the use of partial function and decorator

## Partial: to set up certain keyword arguments before hand

In [ ]:
def sum_func(a,b): return a+b

sum_func(1,2)

3

In [ ]:
sum_func2 = partial(sum_func,1) #add kwargs {a:1} to sum_func
sum_func2(2) # only need to provide argument b

3

## Decorator: wrappers to existing functions, to reuse/ add new functionality to existing functions

In [ ]:
def sum_func(a,b): return a+b # the existing function

In [ ]:
def deco(f):
    def _func(a,b): return f(a,b) # does nothing
    return _func

In [ ]:
my_func = deco(sum_func)
my_func(1,2)

3

In [ ]:
def deco(f):
    def _func(a,b): return 1+ f(a,b) # does new thing to existing f, e.g. increase value by 1
    return _func

my_func = deco(sum_func)
my_func(1,2)

4

or use decorator

In [ ]:
@deco
def sum_func(a,b): return a+b

In [ ]:
my_func = sum_func # deco function (with sum_func as parameter) is called, and _func is returned (without any input params)
my_func(1,2) # put params a and b

4

## Combine decorator and partial

To reuse/add new stuff to existing functions and set up certain kwargs before hand

In [ ]:
def deco(f):
    def _func(a,b): return partial(f,a,b) # note that this function returns a partial function, not a value like above
    return _func

@deco
def sum_func(a,b,c): return a+b+c

In [ ]:
my_func = sum_func(1,2) # deco is called, _func is returned. _func is provided 2 input for parameters a and b
my_func(3) # provide argument c

6

In [ ]:
my_func2 = sum_func(3,3) # my_func2 is a NEW variety of the old function sum_func (because of new kwargs)
my_func2(3)

9

# Normalization, type notation to work with tuple

In [ ]:
def norm(x,m,s): return (x-m)/s

In [ ]:
t[12:14]

tensor([[  0,   0,   0,   0,   0,   0,   0,   0, 164, 239,  26,   0,   0,   0,
           0,  96, 236,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,  12,  47,   0,   0,   0,   0,
           0, 179, 235,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],
       dtype=torch.uint8)

In [ ]:
t = t_float # t is now float

In [ ]:
t.type()

'torch.FloatTensor'

In [ ]:
n_img = norm(t,127,50)
n_img[12:14]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
n_img.mean()

tensor(-2.2250)

In [ ]:
@Transform
def norm(x,m,s): return (x-m)/s

In [ ]:
tupl = (t,1) # assume a image t with label '1'

# normalization is (or should be) done on the gpu, and it will be in a 'batch' form with a bunch of tuple of (image, label)

In [ ]:
temp = norm(tupl,m=127,s=50) # need keywords for @Transform norm
temp[0][12:15],temp[1] # but we don't want label to get transformed

(tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
           0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
           2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
           2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
           1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400]]), -2.52)

In [ ]:
@Transform
def norm(x:torch.Tensor,m,s): return (x-m)/s #type notation added: determine which of the tuple to apply tfm

# # equivalent to
# def _norm(x: torch.Tensor,m,s): return (x-m)/s
# norm = Transform(_norm)

In [ ]:
temp = norm(tupl,m=127,s=50)
temp[0][12:15],temp[1] # fixed!

(tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
           0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
           2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
           2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
           1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400]]), 1)

In [ ]:
tupl2 = (t,t,1)
temp2 = norm(tupl2,m=127,s=50)

In [ ]:
temp2[0][12:15],temp2[1][12:15],temp2[2]

(tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
           0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
           2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
           2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
           1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400]]),
 tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
           0.7400,  2.2400, -2.0200, 

In [ ]:
tupl2 = ((t),(1))
temp2 = norm(tupl2,m=127,s=50)
temp2[0][12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
          1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
tupl2 = ((t,t)) # with tuple size 1, auto simplify to (t,t)
temp2 = norm(tupl2,m=127,s=50)
temp2[0][12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
          1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
# note that tuple of tuple won't work. Conclusion: @Transform meaning it will goes to each value of a tuple 
# (after tuple simplification). If value of a tuple is not torch.Tensor as described => don't transform.
tupl2 = ((t,1),t) # tuple2[0] is not torch.Tensor, tupl2[1] is
temp2 = norm(tupl2,m=127,s=50)
temp2[0][0][12:15],temp2[1][12:15]

(tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 164., 239.,  26.,   0.,
            0.,   0.,   0.,  96., 236.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  12.,  47.,   0.,   0.,
            0.,   0.,   0., 179., 235.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   8., 223., 222.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.]]),
 tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
           0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
           2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.3000, -1.6000

In [ ]:
# equivalent to this long ass custom Transform class (good for pipeline I guess)
class NormTfm(Transform):
    def __init__(self,m,s):
        self.m,self.s = m,s
    def encodes(self,x:torch.Tensor): 
        return (x-self.m)/self.s
    
norm = NormTfm(m=127,s=50)
temp_pipe= Pipeline([norm],as_item=False)
temp =temp_pipe(tupl)

temp[0][12:15],temp[1]

(tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
           0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
           2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
           2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
           1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400]]), 1)

# Semantic markers to existing type

In [ ]:
??TensorBase

In [ ]:
class MyTensorImg(TensorBase): pass # Note: this is just a fastai wrapper class for pytorch FloatTensor
# Answer: fastai wants to add 'semantic markers' to original type to represent 'different kinds of information' (such as to show using show()),
# aside from what the original type has to offer


In [ ]:
my_t = MyTensorImg(t)

In [ ]:
type(my_t),type(t),t.type()

(__main__.MyTensorImg, torch.Tensor, 'torch.FloatTensor')

In [ ]:
@Transform
def norm(x:torch.Tensor,m,s): return (x-m)/s

In [ ]:
norm(t,m=127,s=50)[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
          1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
norm(my_t,m=127,s=50)[12:15] # still works
#because MyTensorImage is a child of torch.Tensor, as type notation will allow children of the type specified in the func

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
          1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
@Transform
def norm2(x:MyTensorImg,m,s): return (x-m)/s 

In [ ]:
norm2(t,m=127,s=50)[12:15] # not working, since torch.Tensor is not the same or children of MyTensorImg

tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 164., 239.,  26.,   0.,
           0.,   0.,   0.,  96., 236.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  12.,  47.,   0.,   0.,
           0.,   0.,   0., 179., 235.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   8., 223., 222.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.]])

In [ ]:
norm2(my_t,m=127,s=50)[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
          1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

# Inherit from Transform (to keep a state/attribute for your transformation + use encodes/decodes)

Remember to 'encode'

In [ ]:
class Norm(Transform):
    def __init__(self,m,s):
        super().__init__()
#         store_attr(self,'m,s')
        self.m,self.s = m,s
    def encodes(self,x:torch.Tensor): return (x-self.m)/self.s
    def encodes(self,x: MyTensorImg): return (x-self.m)/self.s
    # add other type for encodes here if you want
    
    def decodes(self,x: MyTensorImg): return (x*self.s)+ self.m

In [ ]:
# equivalent. You can add encode/decode dynamically
# class Norm(Transform):
#     def __init__(self,m,s):
#         super().__init__()
#         self.m,self.s = m,s

In [ ]:
# @Norm
# def encodes(self,x:torch.Tensor): return (x-self.m)/self.s

In [ ]:
# @Norm
# def encodes(self,x:MyTensorImg): return (x-self.m)/self.s

In [ ]:
type(my_t),type(t)

(__main__.MyTensorImg, torch.Tensor)

In [ ]:
f = Norm(m=127,s=50)
f(my_t)[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
          1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
f(t)[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
          1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
my_t_norm = f(my_t)

In [ ]:
f.decodes(my_t_norm)[12:15]

tensor([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000, 164.0000, 239.0000,  26.0000,   0.0000,   0.0000,   0.0000,
           0.0000,  96.0000, 236.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,  12.0000,  47.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000, 179.0000, 235.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           8.0000, 223.0000, 222.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000]])

# Multiple transform in one go = Pipeline

## option 1: use compose

In [ ]:
x = torch.arange(9).view(3,3)
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
torch.flip(x,[1])

tensor([[2, 1, 0],
        [5, 4, 3],
        [8, 7, 6]])

In [ ]:
@Transform
def flip_img(x:MyTensorImg): return torch.flip(x,[1]) # flip among axis 1

In [ ]:
f_norm =Norm(m=127,s=50)
f_compose = compose(f_norm,flip_img)

In [ ]:
temp = f_compose(my_t)
type(temp),type(my_t), temp.type(),my_t.type() # type reserve

(__main__.MyTensorImg,
 __main__.MyTensorImg,
 'torch.FloatTensor',
 'torch.FloatTensor')

Note that torch.flip won't reserve fastai type using type(), but at the @Transform decorator and it will

In [ ]:
type(torch.flip(my_t,[1])),torch.flip(my_t,[1]).type() #not reserve because torch.flip return tensor type

(torch.Tensor, 'torch.FloatTensor')

In [ ]:
type(flip_img(my_t)),flip_img(my_t).type() #force reserve

(__main__.MyTensorImg, 'torch.FloatTensor')

In [ ]:
temp[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400,  2.1800, -0.6200, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.0200,  2.2400,  0.7400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400,  2.1600,  1.0400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -1.6000, -2.3000, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400,  1.9000,  1.9200, -2.3800, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
# but no decode
f_compose.decode

AttributeError: 'function' object has no attribute 'decode'

In [ ]:
flip_img.decode # thanks to @Transform, flip_img can still have a dummy decode function

<bound method Transform.decode of Transform: True (MyTensorImg,object) -> flip_img >

## option 2: use pipeline

In [ ]:
Pipeline??

In [ ]:
# note that Pipeline will convert everything into Transform, so no need for Transform annotation like in option 1

# @Transform: this is no need
def flip_img(x:MyTensorImg): return torch.flip(x,[1]) # flip among axis 1

In [ ]:
f_norm =Norm(m=127,s=50)

In [ ]:
p = Pipeline([f_norm,flip_img])
temp = p(my_t)
temp[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400,  2.1800, -0.6200, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.0200,  2.2400,  0.7400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400,  2.1600,  1.0400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -1.6000, -2.3000, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400,  1.9000,  1.9200, -2.3800, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
type(temp),temp.type() # Pipeline also do type reserve

(__main__.MyTensorImg, 'torch.FloatTensor')

In [ ]:
type(p.decode(temp)) # reserve original type when decode as well

__main__.MyTensorImg

In [ ]:
p.decode(temp)[12:15] # note that only f_norm decode is called. flip_img does not have decode

tensor([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000, 236.0000,  96.0000,   0.0000,
           0.0000,   0.0000,   0.0000,  26.0000, 239.0000, 164.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000, 235.0000, 179.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,  47.0000,  12.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000, 222.0000, 223.0000,   8.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000]])

### With tuple as input

In [ ]:
type(my_t)

__main__.MyTensorImg

In [ ]:
my_t_tuple = (my_t,1)

In [ ]:
p = Pipeline([f_norm,flip_img])
temp = p(my_t_tuple)
temp[0][12:15],temp[1]

(tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400,  2.1800, -0.6200, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.0200,  2.2400,  0.7400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400,  2.1600,  1.0400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -1.6000, -2.3000, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400,  1.9000,  1.9200, -2.3800, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400]]), 1)

In [ ]:
p = Pipeline([f_norm,flip_img],as_item=True) # note again: as_item=True will force the input as a whole object. So this object is gonna be type 'Tuple'
temp = p(my_t_tuple)
temp[0][12:15],temp[1] #there is no encode(...,o:Tuple), so no transformation is performed

(tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 164., 239.,  26.,   0.,
            0.,   0.,   0.,  96., 236.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  12.,  47.,   0.,   0.,
            0.,   0.,   0., 179., 235.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   8., 223., 222.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.]]), 1)

# Specify output of function (not working)

In [ ]:
@Transform
def create_image_tensor(x): return tensor(array(load_image(x)))

In [ ]:
fn

PosixPath('/home/quantran/.fastai/data/mnist_tiny/train/7/9286.png')

In [ ]:
temp = create_image_tensor(fn)
type(temp),temp.type()

(torch.Tensor, 'torch.ByteTensor')

In [ ]:
# specify/cast output type (NOT WORKING NOW)
@Transform
def create_image_tensor(x)->TensorImage: return tensor(array(load_image(x)))

In [ ]:
temp = create_image_tensor(fn)
type(temp) #TODO: that does not work... it should return fastai torch_core.TensorImage

pathlib.PosixPath

In [ ]:
type(Pipeline(create_image_tensor)(fn))

torch.Tensor

In [ ]:
??TupleTransform

# Metaclass

From my own note: https://colab.research.google.com/drive/1FN8JmmY7nr0fHJ4bTkTOYOrkGQzhKyyB#scrollTo=VS4D0EoBKJVS


type: a class to construct other classes

In [ ]:
class Foo(object): 
    a=1
type(Foo),type(Foo())

(type, __main__.Foo)

In [ ]:
Foo.__dict__

mappingproxy({'__module__': '__main__',
              'a': 1,
              '__dict__': <attribute '__dict__' of 'Foo' objects>,
              '__weakref__': <attribute '__weakref__' of 'Foo' objects>,
              '__doc__': None})

In [ ]:
# equivalent
Foo = type('Foo',(object,),{'a':1})
type(Foo),type(Foo())


(type, __main__.Foo)

In [ ]:
Foo.__dict__ # notice that in both cases, the class attribute 'a' is stored in __dict__

mappingproxy({'a': 1,
              '__module__': '__main__',
              '__dict__': <attribute '__dict__' of 'Foo' objects>,
              '__weakref__': <attribute '__weakref__' of 'Foo' objects>,
              '__doc__': None})

Also note that Foo will inherit every function in type, because it's a 'type' type. Try to do Foo._ and tab for autocompletion

## Create your own 'type': a class to construct other classes

In [ ]:
type??

In [ ]:
class _M(type):
    def __new__(cls,name,bases,dict):
        print('__new__ in _M')
        return super().__new__(cls,name,bases,dict)
    
    @classmethod
    def __prepare__(cls,name,bases): return {'a':1} 
    # to add class attributes to anything constructed by this _M (will be shown in __dict__)

In [ ]:
class T(metaclass= _M): # construct class T using _M as a metaclass
    def some_func(self): return 'some_func'

__new__ in _M


In [ ]:
T.__dict__

mappingproxy({'a': 1,
              '__module__': '__main__',
              'some_func': <function __main__.T.some_func(self)>,
              '__dict__': <attribute '__dict__' of 'T' objects>,
              '__weakref__': <attribute '__weakref__' of 'T' objects>,
              '__doc__': None})

In [ ]:
T.a

1

In [ ]:
T.some_func

<function __main__.T.some_func(self)>

In [ ]:
temp = T()
print(temp.some_func())
print(temp)
print(temp.__dict__)

some_func
{}


# Metaclass of Transform: _TfmMeta

In [ ]:
_tfm_methods = 'encodes','decodes','setups'

class _TfmDict(dict):
    def __setitem__(self,k,v):
        if k not in _tfm_methods or not callable(v): return super().__setitem__(k,v) # if not encodes, decodes or setups, act like a normal dict
        if k not in self: super().__setitem__(k,TypeDispatch()) #if self does not already have 1 of those 3, create one and set it to TypeDispatch (?)
        self[k].add(v)

class _TfmMeta(type):
    def __new__(cls, name, bases, dict): 
        # this is called when only definition of class is created, not when an instance of that class is created. See above
        # i.e. when you do class Transform(metaclass=_TfmMeta): pass 
        res = super().__new__(cls, name, bases, dict)
        res.__signature__ = inspect.signature(res.__init__)
        return res

    def __call__(cls, *args, **kwargs):
        f = args[0] if args else None
        n = getattr(f,'__name__',None)
        for nm in _tfm_methods:
            if not hasattr(cls,nm): setattr(cls, nm, TypeDispatch())
        if callable(f) and n in _tfm_methods:
            getattr(cls,n).add(f)
            return f
        return super().__call__(*args, **kwargs)

    @classmethod
    def __prepare__(cls, name, bases): return _TfmDict() 
    #set TypeDispatch for special 3 functions. This will achieve 'TypeAnnotation' behavior in fastai v2

In [ ]:
class A(metaclass=_TfmMeta):
    def encodes(self,x): return x
    def encodes(self,x:int): return x
    def encodes(self,x:float): return x
    def sum_func(self): return

In [ ]:
A.__dict__

mappingproxy({'__module__': '__main__', 'encodes': (float,object) -> encodes
              (int,object) -> encodes
              (object,object) -> encodes, 'sum_func': <function __main__.A.sum_func(self)>, '__dict__': <attribute '__dict__' of 'A' objects>, '__weakref__': <attribute '__weakref__' of 'A' objects>, '__doc__': None, '__signature__': <Signature (self, /, *args, **kwargs)>})

In [ ]:
A.encodes

(float,object) -> encodes
(int,object) -> encodes
(object,object) -> encodes

In [ ]:
type(A.encodes)

local.core.dispatch.TypeDispatch

In [ ]:
A.sum_func,type(A.sum_func) # not 1 of those 3 things, so behave normally

(<function __main__.A.sum_func(self)>, function)